using System.Text;
using System.Text.Json;
using EnergoSolutions_03.Abstraction;
using EnergoSolutions_03.Models.Agent;

namespace EnergoSolutions_03.Agents;

public class ReportAgent : IReportAgent
{
    private readonly IOpenAIService _openAi;

    public ReportAgent(IOpenAIService openAi)
    {
        _openAi = openAi;
    }

    public async Task<AgentResponse> GenerateReport(Session session)
    {
        // Provide the model with the full Session.UserData as JSON so it can read all details.
        var userDataJson = JsonSerializer.Serialize(session, new JsonSerializerOptions { WriteIndented = true });

        var systemMessage = @"You are a professional Slovak energy consultant. You will be given the complete object Session as JSON. Read it carefully and use only the provided data when producing the report. Produce a polished, user-facing report in Slovak. The report must be returned in Markdown and include the following sections: Analysis, Recommendations, Economics, Implementation Plan, Conclusion. Use a professional and motivating tone. Do not mention that the text was generated by AI. In the Conclusion section provide a short motivating summary (exactly 3-4 sentences). Ensure numeric values from the data are preserved (e.g., yearly savings, costs, payback) and shown with appropriate units (€ and years).";

        var userPrompt = $"Session JSON:\n{userDataJson}\n\nNow, based exclusively on the Session.UserData above, generate the complete report as requested in the system message.";

        // Ask OpenAI to generate the entire report based on the serialized user data
        var aiResult = await _openAi.CreateResponseAsync(systemMessage, userPrompt, model: "gpt-4.1");

        // If OpenAI returns null/empty, return a minimal fallback message
        var finalReport = string.IsNullOrWhiteSpace(aiResult)
            ? "OpenAI did not return a report for the provided data."
            : aiResult;

        return new AgentResponse
        {
            Message = finalReport,
            IsComplete = true,
            Progress = 100
        };
    }
}
